default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  username: postgres
  password: postgres
  database: mb_tools_test

#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
